runtime: nodejs18
env: standard
service: default

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.8 # default value 0.6
  min_instances: 1
  max_instances: 1
  min_pending_latency: 30ms # default value 30ms
  max_pending_latency: automatic # default value 30ms
  max_concurrent_requests: 10

env_variables:
  NODE_ENV: development
  PORT: 8080

# handlers:
#   - url: /
#     static_files: index.html
#     require_matching_file: false
#     upload: index.html
#   - url: /(.*)
#     static_files: \1
#     require_matching_file: false
#     upload: .*
#   - url: .*
#     script: auto

# handlers:
#   # Serve all static files with url ending with a file extension
#   - url: /(.*\..+)$
#     static_files: build/\1
#     upload: build/(.*\..+)$
#   # Catch all handler to index.html
#   -url: /.*
#     static_files: build/index.html
#     secure: always
#     redirect_http_response_code: 301
#     script: auto


handlers:
  - url: /static/js/(.*)
    static_files: build/static/js/\1
    upload: build/static/js/(.*)
  - url: /static/css/(.*)
    static_files: build/static/css/\1
    upload: build/static/css/(.*)
  - url: /static/media/(.*)
    static_files: build/static/media/\1
    upload: build/static/media/(.*)
  - url: /(.*\.(json|ico))$
    static_files: build/\1
    upload: build/.*\.(json|ico)$
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html